const departmentsAndCities = {
  departments: [
    {
      id: 1,
      name: "Atlántida",
      cities: [
        { id: 1, name: "La Ceiba" },
        { id: 2, name: "Tela" },
        { id: 3, name: "Jutiapa" },
        { id: 4, name: "La Masica" },
        { id: 5, name: "San Francisco" },
        { id: 6, name: "Arizona" },
        { id: 7, name: "Esparta" },
        { id: 8, name: "El Porvenir" },
      ],
    },
    {
      id: 2,
      name: "Colón",
      cities: [
        { id: 1, name: "Trujillo" },
        { id: 2, name: "Balfate" },
        { id: 3, name: "Iriona" },
        { id: 4, name: "Limón" },
        { id: 5, name: "Sabá" },
        { id: 6, name: "Santa Fe" },
        { id: 7, name: "Santa Rosa de Aguán" },
        { id: 8, name: "Sonaguera" },
        { id: 9, name: "Tocoa" },
        { id: 10, name: "Bonito Oriental" },
      ],
    },
    {
      id: 3,
      name: "Comayagua",
      cities: [
        { id: 1, name: "Comayagua" },
        { id: 2, name: "Ajuterique" },
        { id: 3, name: "El Rosario" },
        { id: 4, name: "Esquías" },
        { id: 5, name: "Humuya" },
        { id: 6, name: "La libertad" },
        { id: 7, name: "Lamaní" },
        { id: 8, name: "La Trinidad" },
        { id: 9, name: "Lejamani" },
        { id: 10, name: "Meambar" },
        { id: 11, name: "Minas de Oro" },
        { id: 12, name: "Ojos de Agua" },
        { id: 13, name: "San Jerónimo" },
        { id: 14, name: "San José de Comayagua" },
        { id: 15, name: "San José del Potrero" },
        { id: 16, name: "San Luis" },
        { id: 17, name: "San Sebastián" },
        { id: 18, name: "Siguatepeque" },
        { id: 19, name: "Villa de San Antonio" },
        { id: 20, name: "Las Lajas" },
        { id: 21, name: "Taulabé" },
      ],
    },
    {
      id: 4,
      name: "Copán",
      cities: [
        { id: 1, name: "Santa Rosa de Copán" },
        { id: 2, name: "Cabañas" },
        { id: 3, name: "Concepción" },
        { id: 4, name: "Copán Ruinas" },
        { id: 5, name: "Corquín" },
        { id: 6, name: "Cucuyagua" },
        { id: 6, name: "Dolores" },
        { id: 8, name: "Dulce Nombre" },
        { id: 9, name: "El Paraíso" },
        { id: 10, name: "Florida" },
        { id: 11, name: "La Jigua" },
        { id: 12, name: "La Unión" },
        { id: 13, name: "Nueva Arcadia" },
        { id: 14, name: "San Agustín" },
        { id: 15, name: "San Antonio" },
        { id: 16, name: "San Jerónimo" },
        { id: 17, name: "San José" },
        { id: 18, name: "San Juan de Opoa" },
        { id: 19, name: "San Nicolás" },
        { id: 20, name: "San Pedro" },
        { id: 21, name: "Santa Rita" },
        { id: 22, name: "Trinidad de Copán" },
        { id: 23, name: "Veracruz" },
      ],
    },
    {
      id: 5,
      name: "Cortés",
      cities: [
        { id: 1, name: "San Pedro Sula" },
        { id: 2, name: "Choloma" },
        { id: 3, name: "Omoa" },
        { id: 4, name: "Pimienta" },
        { id: 5, name: "Potrerillos" },
        { id: 6, name: "Puerto Cortés" },
        { id: 7, name: "San Antonio de Cortés" },
        { id: 8, name: "San Francisco de Yojoa" },
        { id: 9, name: "San Manuel" },
        { id: 10, name: "Santa Cruz de Yojoa" },
        { id: 11, name: "Villanueva" },
        { id: 12, name: "La Lima" },
      ],
    },
    {
      id: 6,
      name: "Choluteca",
      cities: [
        { id: 1, name: "Choluteca" },
        { id: 2, name: "Apacilagua" },
        { id: 3, name: "Concepción de María" },
        { id: 4, name: "Duyure" },
        { id: 5, name: "El Corpus" },
        { id: 6, name: "El Triunfo" },
        { id: 7, name: "Marcovia" },
        { id: 8, name: "Morolica" },
        { id: 9, name: "Namasigue" },
        { id: 10, name: "Orocuina" },
        { id: 11, name: "Pespire" },
        { id: 12, name: "San Antonio de Flores" },
        { id: 13, name: "San Isidro" },
        { id: 14, name: "San José" },
        { id: 15, name: "San Marcos de Colón" },
        { id: 16, name: "Santa Ana de Yusguare" },
      ],
    },
    {
      id: 7,
      name: "El Paraíso",
      cities: [
        { id: 1, name: "Yuscarán" },
        { id: 2, name: "Alauca" },
        { id: 3, name: "Danlí" },
        { id: 4, name: "El Paraíso" },
        { id: 5, name: "Güinope" },
        { id: 6, name: "Jacaleapa" },
        { id: 7, name: "Liure" },
        { id: 8, name: "Morocelí" },
        { id: 9, name: "Oropolí" },
        { id: 10, name: "Potrerillos" },
        { id: 11, name: "San Antonio de Flores" },
        { id: 12, name: "San Lucas" },
        { id: 13, name: "San Matías" },
        { id: 14, name: "Soledad" },
        { id: 15, name: "Teupasenti" },
        { id: 16, name: "Texiguat" },
        { id: 17, name: "Vado Ancho" },
        { id: 18, name: "Yauyupe" },
        { id: 19, name: "Trojes" },
      ],
    },
    {
      id: 8,
      name: "Francisco Morazán",
      cities: [
        { id: 1, name: "Distrito Central" },
        { id: 2, name: "Alubarén" },
        { id: 3, name: "Cedros" },
        { id: 4, name: "Curarén" },
        { id: 5, name: "El Porvenir" },
        { id: 6, name: "Guaimaca" },
        { id: 7, name: "La Libertad" },
        { id: 8, name: "La Venta" },
        { id: 9, name: "Lepaterique" },
        { id: 10, name: "Maraita" },
        { id: 11, name: "Marale" },
        { id: 12, name: "Nueva Armenia" },
        { id: 13, name: "Ojojona" },
        { id: 15, name: "Orica" },
        { id: 16, name: "Reitoca" },
        { id: 17, name: "Sabanagrande" },
        { id: 18, name: "San Antonio de Oriente" },
        { id: 19, name: "San Buenaventura" },
        { id: 20, name: "San Ignacio" },
        { id: 21, name: "San Juan de Flores" },
        { id: 22, name: "San Miguelito" },
        { id: 23, name: "Santa Ana" },
        { id: 24, name: "Santa Lucía" },
        { id: 25, name: "Talanga" },
        { id: 26, name: "Tatumbla" },
        { id: 27, name: "Valle de Ángeles" },
        { id: 28, name: "Villa de San Francisco" },
        { id: 29, name: "Vallecillo" },
      ],
    },
    {
      id: 9,
      name: "Gracias a Dios",
      cities: [
        { id: 1, name: "Puerto Lempira" },
        { id: 1, name: "Brus Laguna" },
        { id: 1, name: "Ahuas" },
        { id: 1, name: "Juan Francisco Bulnes" },
        { id: 1, name: "Ramón Villeda Morales" },
        { id: 1, name: "Wampusirpe" },
      ],
    },
    {
      id: 10,
      name: "Intibucá",
      cities: [
        { id: 1, name: "La Esperanza" },
        { id: 2, name: "Camasca" },
        { id: 3, name: "Colomoncagua" },
        { id: 4, name: "Concepción" },
        { id: 5, name: "Dolores" },
        { id: 6, name: "Intibucá" },
        { id: 7, name: "Jesús de Otoro" },
        { id: 8, name: "Magdalena" },
        { id: 9, name: "Masaguara" },
        { id: 10, name: "San Antonio" },
        { id: 11, name: "San Isidro" },
        { id: 12, name: "San Juan" },
        { id: 13, name: "San Marcos de la Sierra" },
        { id: 14, name: "San Miguel Guancapla" },
        { id: 15, name: "Santa Lucía" },
        { id: 16, name: "Yamaranguila" },
        { id: 17, name: "San Francisco de Opalaca" },
      ],
    },
    {
      id: 11,
      name: "Islas de la Bahía",
      cities: [
        { id: 1, name: "Roatán" },
        { id: 2, name: "Guanaja" },
        { id: 3, name: "José Santos Guardiola" },
        { id: 4, name: "Utila" },
      ],
    },
    {
      id: 12,
      name: "La Paz",
      cities: [
        { id: 1, name: "La Paz" },
        { id: 2, name: "Aguanqueterique" },
        { id: 3, name: "Cabañas" },
        { id: 4, name: "Cane" },
        { id: 5, name: "Chinacla" },
        { id: 6, name: "Guajiquiro" },
        { id: 7, name: "Lauterique" },
        { id: 8, name: "Marcala" },
        { id: 9, name: "Mercedes de Oriente" },
        { id: 10, name: "Opatoro" },
        { id: 11, name: "San Antonio del Norte" },
        { id: 12, name: "San José" },
        { id: 13, name: "San Juan" },
        { id: 14, name: "San Pedro de Tutule" },
        { id: 15, name: "Santa Ana" },
        { id: 16, name: "Santa Elena" },
        { id: 17, name: "Santa María" },
        { id: 18, name: "Santiago de Puringla" },
        { id: 19, name: "Yarula" },
      ],
    },
    {
      id: 13,
      name: "Lempira",
      cities: [
        { id: 1, name: "Gracias" },
        { id: 2, name: "Belén" },
        { id: 3, name: "Candelaria" },
        { id: 4, name: "Cololaca" },
        { id: 5, name: "Erandique" },
        { id: 6, name: "Gualcince" },
        { id: 7, name: "Guarita" },
        { id: 8, name: "La Campa" },
        { id: 9, name: "La Iguala" },
        { id: 10, name: "Las Flores" },
        { id: 11, name: "La Unión" },
        { id: 12, name: "La Virtud" },
        { id: 13, name: "Lepaera" },
        { id: 14, name: "Mapulaca" },
        { id: 15, name: "Piraera" },
        { id: 16, name: "San Andrés" },
        { id: 17, name: "San Francisco" },
        { id: 18, name: "San Juan Guarita" },
        { id: 19, name: "San Manuel Colohete" },
        { id: 20, name: "San Rafael" },
        { id: 21, name: "San Sebastián" },
        { id: 22, name: "Santa Cruz" },
        { id: 23, name: "Talgua" },
        { id: 24, name: "Tambla" },
        { id: 25, name: "Tomalá" },
        { id: 26, name: "Valladolid" },
        { id: 27, name: "Virginia" },
        { id: 28, name: "San Marcos de Caiquín" },
      ],
    },
    {
      id: 14,
      name: "Ocotepeque",
      cities: [
        { id: 1, name: "Ocotepeque" },
        { id: 2, name: "Belén Gualcho" },
        { id: 3, name: "Concepción" },
        { id: 4, name: "Dolores Merendón" },
        { id: 5, name: "Fraternidad" },
        { id: 6, name: "La Encarnación" },
        { id: 7, name: "La Labor" },
        { id: 8, name: "Lucerna" },
        { id: 9, name: "Mercedes" },
        { id: 10, name: "San Fernando" },
        { id: 11, name: "San Francisco del Valle" },
        { id: 12, name: "San Jorge" },
        { id: 13, name: "San Marcos" },
        { id: 14, name: "Santa Fe" },
        { id: 15, name: "Sensenti" },
        { id: 16, name: "Sinuapa" },
      ],
    },
    {
      id: 15,
      name: "Olancho",
      cities: [
        { id: 1, name: "Juticalpa" },
        { id: 2, name: "Campamento" },
        { id: 3, name: "Catacamas" },
        { id: 4, name: "Concordia" },
        { id: 5, name: "Dulce Nombre de Culmí" },
        { id: 6, name: "El Rosario" },
        { id: 7, name: "Esquipulas del Norte" },
        { id: 8, name: "Gualaco" },
        { id: 9, name: "Guarizama" },
        { id: 10, name: "Guata" },
        { id: 11, name: "Guayape" },
        { id: 12, name: "Jano" },
        { id: 13, name: "La Unión" },
        { id: 14, name: "Mangulile" },
        { id: 15, name: "Manto" },
        { id: 16, name: "Salamá" },
        { id: 17, name: "San Esteban" },
        { id: 18, name: "San Francisco de Becerra" },
        { id: 19, name: "San Francisco de la Paz" },
        { id: 20, name: "Santa María del Real" },
        { id: 21, name: "Silca" },
        { id: 22, name: "Yocón" },
        { id: 23, name: "Patuca" },
      ],
    },
    {
      id: 16,
      name: "Santa Bárbara",
      cities: [
        { id: 1, name: "Santa Bárbara" },
        { id: 2, name: "Arada" },
        { id: 3, name: "Atima" },
        { id: 4, name: "Azacualpa" },
        { id: 5, name: "Ceguaca" },
        { id: 6, name: "Concepción del Norte" },
        { id: 7, name: "Concepción del Sur" },
        { id: 8, name: "Chinda" },
        { id: 9, name: "El Níspero" },
        { id: 10, name: "Gualala" },
        { id: 11, name: "Ilama" },
        { id: 12, name: "Las Vegas" },
        { id: 13, name: "Macuelizo" },
        { id: 14, name: "Naranjito" },
        { id: 15, name: "Nuevo Celilac" },
        { id: 16, name: "Nueva Frontera" },
        { id: 17, name: "Petoa" },
        { id: 18, name: "Protección" },
        { id: 19, name: "Quimistán" },
        { id: 20, name: "San Francisco de Ojuera" },
        { id: 21, name: "San José de las Colinas" },
        { id: 22, name: "San Luis" },
        { id: 23, name: "San Marcos" },
        { id: 24, name: "San Nicolás" },
        { id: 25, name: "San Pedro Zacapa" },
        { id: 26, name: "San Vicente Centenario" },
        { id: 27, name: "Santa Rita" },
        { id: 28, name: "Trinidad" },
      ],
    },
    {
      id: 17,
      name: "Valle",
      cities: [
        { id: 1, name: "Nacaome" },
        { id: 2, name: "Alianza" },
        { id: 3, name: "Amapala" },
        { id: 4, name: "Aramecina" },
        { id: 5, name: "Caridad" },
        { id: 6, name: "Goascorán" },
        { id: 7, name: "Langue" },
        { id: 8, name: "San Francisco de Coray" },
        { id: 9, name: "San Lorenzo" },
      ],
    },
    {
      id: 18,
      name: "Yoro",
      cities: [
        { id: 1, name: "Yoro" },
        { id: 2, name: "Arenal" },
        { id: 3, name: "El Negrito" },
        { id: 4, name: "El Progreso" },
        { id: 5, name: "Jocón" },
        { id: 6, name: "Morazán" },
        { id: 7, name: "Olanchito" },
        { id: 8, name: "Santa Rita" },
        { id: 9, name: "Sulaco" },
        { id: 10, name: "Victoria" },
        { id: 11, name: "Yorito" },
      ],
    },
  ],
};

export default departmentsAndCities;
