name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: server
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: server
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: server
    - name: dotnet publish
      run: dotnet publish -c Release -o out 
      working-directory: server
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: telemedicine-server # Replace with your app name
        publish-profile: ${{ secrets.publish_profile }}
        package: 'server/out'
